### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#139]
* При наведении на текст статьи пока скрывать "glyphicon-comment".
* пока скрывать "4-5 minutes30 May, 2014"
* слишком большой отступ для

![image](https://cloud.githubusercontent.com/assets/604410/11589079/275b3e0c-9a8e-11e5-913d-5be3dcaeee56.png)

* переместить ссылку после точки. Убрать знак "$"

![image](https://cloud.githubusercontent.com/assets/604410/11589145/bedfa7c2-9a8e-11e5-9155-02c1cb21ffa2.png)
* убрать возможность изменения размера поля для ввода твита.

**Comment by AlexeyAnshakov** [comment]
При переходе между страницами в Plus пропадает скролл
![image](https://cloud.githubusercontent.com/assets/604410/11612263/98e07d30-9bfb-11e5-9bf1-ef1b1d540ff8.png)

**Comment by Xurma2** [comment]
Можно закрывать?

**Comment by AlexeyAnshakov** [comment]
В iOS правое меню не работает - при нажатии на пункт меню не открывается нужный раздел.

**Comment by Xurma2** [comment]
Судя по эмуляторам работает. К сожалению нет мобильника такого не могу даже предположить из за чего. Посмотрел в разных разрешениях и на андроид, тоже самое

**Comment by AlexeyAnshakov** [comment]
За правым меню ненужный скролл
![image](https://cloud.githubusercontent.com/assets/604410/11911915/882c24e2-a62f-11e5-9d80-7ebcd6689494.png)

**Comment by AlexeyAnshakov** [comment]
Добавить 
>cursor:pointer;

при наведении на правое меню.

**Comment by AlexeyAnshakov** [comment]
При мобильном разрешении правое меню не имеет скролла.

Тикеты логина и вверху в правом меню привести к виду в прототипе
![tickets](https://cloud.githubusercontent.com/assets/604410/12398350/71e3390e-be13-11e5-9de4-65bbae906500.png)
При наведении на тикет не должна быть подчеркивание ссылок, только при наведении на них.

Привести к виду в протипе itemList
>http://webrunes.com/ru/?list=Blog

За пример взять страницу Default-WRIO-Theme/person-list-favorites.htm

**Comment by AlexeyAnshakov** [comment]
Раздел description на странице https://webrunes.com/photos-list.htm
![description](https://cloud.githubusercontent.com/assets/604410/12530440/cdc023f2-c1df-11e5-9464-4168e416aa87.png)

При переходе между табами Plus не всегда отображается соответствующее активное меню либо наоборот двойное (ie)
![bug1](https://cloud.githubusercontent.com/assets/604410/12530468/753ca9d4-c1e0-11e5-8087-41c5ebadf9c5.png)

https://wr.io/
![bug](https://cloud.githubusercontent.com/assets/604410/12530465/6495325e-c1e0-11e5-840c-d0cb700937a6.png)

**Comment by AlexeyAnshakov** [comment]
При нажатии на ссылку не нужно отображать outline
![scr](https://cloud.githubusercontent.com/assets/604410/12535423/09f5056a-c283-11e5-9b23-849b36e4ed0e.png)

**Comment by AlexeyAnshakov** [comment]
Текст в тикетах почему-то синий
https://wr.io/445509666832/Plus-WRIO-App/#
поправить чтобы были как в прототипе Default-WRIO-Theme/plus-apps.htm

**Comment by AlexeyAnshakov** [comment]
При небольших разрешениях баг с тикетами
![bug](https://cloud.githubusercontent.com/assets/604410/12561996/1a96f4de-c3a3-11e5-8799-acfaac8d55c1.png)

**Comment by AlexeyAnshakov** [comment]
Добавить для активного таба линию 2px толщины, цвет #337ab7
![image](https://cloud.githubusercontent.com/assets/604410/13175850/009841ce-d716-11e5-9eb5-5acd058035b9.png)
