### ISSUE TITLE
Инициализация itemList. Reward 28 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#23]
Добавить вставку itemList на страницу при парсинге json-ld.
```
<div itemscope="" itemtype="http://schema.org/ItemList" >...</div>
```
Пример разметки itemList можно найти здесь:
>Default-WRIO-Theme/blogs-list.htm

После нажатия на ссылку списка в меню, отображать данную вставку и данные в ней и скрывать
```
<article itemscope="" itemtype="http://schema.org/Article">...</article>
```
Таким образом, мы остаемся на той же странице хаба.
json-ld для примера выше
>Default-WRIO-Theme\examples\v2\itemList.htm

**Comment by AlexeyAnshakov** [comment]
При переходе 
>http://wall2003.github.io/webRunes-WRIO-Hub/Alexey-Anshakov.html#My list

нельзя вернуться на предыдущие страницы вроде
>http://wall2003.github.io/webRunes-WRIO-Hub/Alexey-Anshakov.html#Personal information

**Comment by wall2003** [comment]
я тоже не понял, почему ты сразу это не сказал...

2015-02-10 10:34 GMT+03:00 Alexey Anshakov <notifications@github.com>:

**Comment by AlexeyAnshakov** [comment]
Не заметил, что неправильно обрабатывается itemList в
>http://wall2003.github.io/webRunes-WRIO-Hub/Alexey-Anshakov.html
Список тикетов itemList прямо в json-ld, а надо чтобы в нем был лишь ссылка на его загрузку как это сделано в примере:
>Default-WRIO-Theme\examples\v2\person.htm

**Comment by wall2003** [comment]
Default-WRIO-Theme\examples\v2\person.htm - здесь json-ld  а не разметка

не понял что ты имеешь ввиду?

16 февраля 2015 г., 8:01 пользователь Alexey Anshakov <
notifications@github.com> написал:

**Comment by AlexeyAnshakov** [comment]
В
>Default-WRIO-Theme\examples\v2\person.htm

json-ld для загрузки списков
```
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "ItemList",
        "name": "My lists",
        "itemListElement": [
        {
              "@type": "ItemList",
              "name": "Blog",
              "description": "Info about list",
              "image": "http://domain1.com/image1.jpg",
              "url": "http://webrunes.com/blog.htm"
        },
        {
              "@type": "ItemList",
              "name": "Photos",
              "description": "Info about list",
              "image": "http://domain.com/image.jpg",
              "url": "http://webrunes.com/photos.htm"
        }
        ]
        }
    </script>
```
и при нажатии надо загружать их (нажал, например, на blog.htm и загрузил список из Default-WRIO-Theme\examples\v2\blog.htm), в сегодняшнем варианте ссылки не на списки содержащие тикеты, а сам список тикетов вставлен прямо в article

**Comment by AlexeyAnshakov** [comment]
Closed due updated reaact based task https://github.com/webRunes/Default-WRIO-Theme/issues/53
