### ISSUE TITLE
Добавление ссылок в статьи. Reward 45 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#27]
В примере
>Default-WRIO-Theme\examples\v2\article-links.htm

Добавлен код отвечающий за ссылки
>"mentions": [
        {
        "@type": "Article",
        "name": "Title of the link",
        "about": "Text inside the ticket popup.",
       "url": "webrunes.com/blog.htm?'dolor sit amet':1,104"
        }
        ]

Этот раздел всегда будет идти в конце статьи, так как может быть только один раздел mentions в json-ld. О name ниже, а about пока не важен. Ссылка говорит какой url открыть при ее нажатии. Более интересны текст и цифры после.
>"url": "webrunes.com/blog.htm?'dolor sit amet':1,1,104"

Первая цифра 1 говорит, что ссылку надо разместить в первом разделе (в примере есть еще ссылки для hasparts), вторая 1 говорит о номере абзаца (в этом разделе) и 104 - номер символа (в этом разделе). Сам текст должен совпасть с текстом идущим после указанного символа и отображаться в виде ссылки. Причем ссылка должна идти не в виде
>webrunes.com/blog.htm?'dolor sit amet':1,1,104

а заменив на name
>webrunes.com/blog.htm?'Title of the link'

Этот подход не очень красив с точки зрения архитектуры, но позволяет создать децентрализованную семантическую сеть json-ld, поисковикам связывать статью с другими страницами, а нам не выходить за рамки schema. Позже будет разработан Core для редактирования в редакторе и автоматической записи ссылок.

Chapter 2 - это пример отображения ссылки в виде тикета, если существует отдельная статья для данного раздела, но ссылка идет не в mentions, а внутри haspart. По структуре это такая же страница, как и пример
>Default-WRIO-Theme\examples\v2\article-links.htm

То как должна выглядеть страница с этими ссылками можно увидеть в прототипе
>Default-WRIO-Theme\examples\The-story-of-the-cat.htm

**Comment by AlexeyAnshakov** [comment]
Небольшое изменение:
```
Причем ссылка должна идти не в виде

webrunes.com/blog.htm?'dolor sit amet':1,1,104
а заменив на name

webrunes.com/blog.htm?'Title of the link'
```
Изменить на 
webrunes.com/blog.htm?Title-of-the-link
из-за транскрипции символов в url в вид
>http://webrunes.com/url.htm?%27Class%20aptent%27

Ссылка на chapter2 в меню должна не открывать эту ссылку, а перескакивать на раздел с тикетом, при нажатии на него уже будет открываться ссылка.

**Comment by wall2003** [comment]
Ссылка на chapter2 в меню должна не открывать эту ссылку, а перескакивать
на раздел с тикетом,

как узнать и где находится разделы и что за разделы? и как на них
перескакивать?

13 февраля 2015 г., 7:30 пользователь Alexey Anshakov <
notifications@github.com> написал:

**Comment by AlexeyAnshakov** [comment]
>Ссылка на chapter2 в меню должна не открывать эту ссылку, а перескакивать на раздел с тикетом, 

>как узнать и где находится разделы и что за разделы? и как на них перескакивать?

Разделы с тикетами ничем не отличаются от просто разделов с текстом, имеют тот же name, разница лишь в том, что в одном случае url, а в другом articleBody с текстом. В примере
>http://wall2003.github.io/webRunes-WRIO-Hub/Alexey-Anshakov.html#Chapter 1

уже все работает как надо, только вместо url в меню для chapter2 надо перескакивать на раздел как это сделано для chapter1, т.е. чтобы была ссылка
>http://wall2003.github.io/webRunes-WRIO-Hub/Alexey-Anshakov.html#Chapter 2

И отображать для chapter2 тикет как это сделано в примере
>Default-WRIO-Theme/examples/The-story-of-the-cat.htm

**Comment by wall2003** [comment]
Ссылка на chapter2 в меню должна не открывать эту ссылку, а перескакивать
на раздел с тикетом,

просто, для этого в json-ld url - должен быть просто соответственный.

16 февраля 2015 г., 8:05 пользователь Alexey Anshakov <
notifications@github.com> написал:

**Comment by AlexeyAnshakov** [comment]
Т.е. соответствующий? url в тикете указывает на то, какую страницу открыть в отдельном табе.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/Default-WRIO-Theme/issues/70
