### ISSUE TITLE
Build. Reward ??? USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#40]
Please make autobuild for
>https://travis-ci.org/webRunes/Default-WRIO-Theme

so we got updated files in
>http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/

At this moment we have new version of
>https://webrunes.github.io/Default-WRIO-Theme/widget/article.htm

and we need it there
>http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/widget/article.htm

**Comment by umairadeeb** [comment]
This was completed.
