### ISSUE TITLE
Build. Reward 4 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#55]
Please add .travis.yml to build through
https://travis-ci.org/webRunes/Default-WRIO-Theme
so files like this one http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/widget/defaultList.htm can be accessed via aws

**Comment by umairadeeb** [comment]
This is configured against https://github.com/webRunes/Default-WRIO-Theme/pull/56

**Comment by AlexeyAnshakov** [comment]
There is an error https://travis-ci.org/webRunes/Default-WRIO-Theme

**Comment by umairadeeb** [comment]
I don't see any error.
https://travis-ci.org/webRunes/Default-WRIO-Theme/builds/62881683

**Comment by AlexeyAnshakov** [comment]
Was fixed
