### ISSUE TITLE
ImageObject

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#76]
http://schema.org/ImageObject
На примере
http://webrunes.com/cover.htm
страница должна рендерится алогично itemList с
http://webrunes.com/blog-list.htm

**Comment by rageofaxe** [comment]
эта задача актуальна? там рендерится одинаково, вроде

**Comment by AlexeyAnshakov** [comment]
Да, все ок. Следующая задача по картинкам: https://github.com/webRunes/Default-WRIO-Theme/issues/111
