### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Default-WRIO-Theme#99]
Fix
>"NetworkError: 404 Not Found - http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/css/webrunes.css"

Check console and fix all errors.

**Comment by Xurma2** [comment]
Я вроде не коммитил, но этих сообщений больше нету

**Comment by AlexeyAnshakov** [comment]
It's there, loot console
>GET http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/css/webrunes.css [HTTP/1.1 404 Not Found 475ms]

**Comment by Xurma2** [comment]
Это не помогло видимо.

**Comment by AlexeyAnshakov** [comment]
Еще пока не на сервере
